apiVersion: v1
kind: Namespace
metadata:
  name: scorpion

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: scorpio
  namespace: scorpion

---

apiVersion: v1
kind: Namespace
metadata:
  name: foo

kind: Pod
apiVersion: v1
metadata:
  name: test
  namespace: foo
spec:
  containers:
  - image: luksa/kubectl-proxy
---

apiVersion: v1
kind: Namespace
metadata:
  name: bar

kind: Pod
apiVersion: v1
metadata:
  name: test
  namespace: bar
spec:
  containers:
  - image: luksa/kubectl-proxy