kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubia
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:v1
        name: nodejs
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
  selector:
    matchLabels:
      app: kubia